### ISSUE TITLE
Disable, not hide, the Ultimate attack

### ISSUE THREAD

**Issue by redbmk** [eframson/sturgeon-rpg#1]
I think it would be better if the thousand cuts attack was always there, but disabled until you're allowed to use it.

Say for example you are fighting some simple monsters and you tend to do the "Basic Stag. Atk." twice to get the stagger up quick, then do some regular attacks. Now, let's say you're only one hit away from getting your ultimate up. You press "Basic Stag. Atk.", then the button gets replaced with the Ultimate attack, and if you're not paying close enough attention you'll try to click the stagger attack but use up your ultimate instead.

**Comment by eframson** [comment]
Fixed in 203c52d31359c6c7ac7b6da772a48a57a2206f8b
